### ISSUE TITLE
Small Issue / Suggestion Re: Filenames

### ISSUE THREAD

**Issue by ENDER3000** [waylaidwanderer/FicSave#51]
Hey, this isn't a major issue but more of a suggestion.

Is it possible to have the file that is downloaded be Author - Title.filetype ? When it downloads for me (I use the MOBI option), it is Title - Author.filetype, which I assume is the norm for the other formats as well.

Thanks for all your hard work! Love this site btw! :D 

-
Ender

**Comment by waylaidwanderer** [comment]
That's kind of smart actually... if you sort it by title it groups the authors together. Now why didn't I think of that?

I just changed the live site as per your suggestion, and I'll close this issue once I push the code to the repo. Thanks!

**Comment by ENDER3000** [comment]
Not a problem! Keep up the great work! :D

**Comment by ENDER3000** [comment]
I just tried it, it does work.

**Comment by chikiko** [comment]
This actually frustrates me to no end.  As i remember stories by their title not by the author.  So when it takes me much longer to find a story, especially since the title name may never show up because file names are sometimes compressed to save space and all you see it the author name.  which means i would then have to click on every file of an author to find the file i'm looking for.  IF i even remember the name of the author who the fic i'm looking for.  But as there are those who prefer author name first can you add a choice box where you can choose title or author name first? that way those who want things filed by author can do so and those who want to see the title name on the file can do so too?

**Comment by chikiko** [comment]
I mention this because i usually open files from either my browser's download list which lists file name, or a file manager which similarly lists files by filename.  please add a choice to file name whether it be story name first or author name.   it's just so frustrating having to search endlessly for a file because you can't see the fic name so i end up having to just redownload a duplicate file because i either can't fine the particular fic because i don't know the author name  or there are just too many fics to go through from an author i do happen to know to find said story.
