### ISSUE TITLE
Format chooser not working in cloned copy

### ISSUE THREAD

**Issue by ReadyP1** [waylaidwanderer/FicSave#94]
Cloned the repo, created a Heroku instance currently running [here](https://tcby-ficsave.herokuapp.com). For some reason, the option for choosing formats is gone entirely (see the instance for details). What's up?

**Comment by waylaidwanderer** [comment]
Probably because you didn't include the necessary javascript files needed for the site to function properly. I noticed you removed the footer; perhaps you also accidentally removed the block of code where all the JS files are included.

Anyway I don't do bug support for forks/cloned instances, but hope what I just told you helps.
